wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value: 2
hidden_size:
  value: 64
learning_rate:
  value: 0.001
optimizer:
  value: momentum
weight_init:
  value: random
