wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers:
  value: 3
hidden_size:
  value: 64
learning_rate:
  value: 0.01
optimizer:
  value: momentum
weight_init:
  value: random
