wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 2
hidden_size:
  value: 64
learning_rate:
  value: 0.01
optimizer:
  value: momentum
weight_init:
  value: random
