wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers:
  value: 3
hidden_size:
  value: 64
learning_rate:
  value: 0.1
optimizer:
  value: sgd
weight_init:
  value: xavier
