_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: sigmoid
batch_size:
    value: 16
epochs:
    value: 5
hidden_layers:
    value: 5
hidden_size:
    value: 128
learning_rate:
    value: 0.0001
optimizer:
    value: momentum
weight_decay:
    value: 0
weight_init:
    value: random
