_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 10
hidden_layers:
    value: 2
hidden_size:
    value: 64
learning_rate:
    value: 0.001
optimizer:
    value: momentum
weight_init:
    value: xavier
